name: Build debian package
on:
  #workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        fetch-depth: "0"

    - name: Install extra packages
      run: |
        sudo apt-get update
        sudo apt-get install git git2cl lintian debhelper

    - name: Show info
      run: make info

    - name: Create deb package
      run: make deb

    - name: Display artifacts
      run: ls -R xdocker-make_*_all.deb
      working-directory: .

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ver=0.0
        echo "ver=$ver"
        tag=release-$(make version)-$(date +%Y%m%d-%H%M%S)
        echo "tag=$tag"
        echo "gh release create --latest --title ${tag} ${tag} $(find . -name 'xdocker-make_*_all.deb')"
        gh release create --latest --title ${tag} ${tag} $(find . -name 'xdocker-make_*_all.deb')
